theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
name: Learn modern PHP

# Name of website (site.title)
title: Learn modern PHP

# Short description of your site
description: PHP is cool

# url is the full website URL
# baseurl is the website's URL without the hostname
url: https://odan.github.io
baseurl: "/learn-php"

google_analytics: UA-135965119-1
